name: Sync Repository Secrets

on:
  workflow_dispatch: {}  # No inputs needed, will sync all secrets from mapping

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

      - name: Process Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Read all secret names from mapping.json
          SECRET_NAMES=$(jq -r 'keys[]' mapping.json)
          
          # Process each secret
          echo "$SECRET_NAMES" | while read -r secret_name; do
            # Get the secret value using indirect reference
            secret_value="${{ secrets[format('{0}', secret_name)] }}"
            
            if [ -z "$secret_value" ]; then
              echo "Warning: Secret '$secret_name' not found in repository secrets"
              continue
            fi
            
            # Get target repositories for this secret
            target_repos=$(jq -r --arg secret "$secret_name" '.[$secret][]' mapping.json)
            
            # Sync to each target repository
            echo "$target_repos" | while read -r repo; do
              if [ ! -z "$repo" ]; then
                echo "Syncing secret '$secret_name' to repository '$repo'"
                echo "$secret_value" | gh secret set "$secret_name" --body-file - --repo "$repo"
              fi
            done
          done
