name: Sync Repository Secrets

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to sync'
        required: true
        type: string

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

      - name: Read mapping file
        id: read-mapping
        run: |
          MAPPING=$(cat mapping.json)
          echo "mapping=$MAPPING" >> $GITHUB_OUTPUT

      - name: Get target repositories
        id: get-repos
        run: |
          SECRET_NAME="${{ github.event.inputs.secret_name }}"
          REPOS=$(echo '${{ steps.read-mapping.outputs.mapping }}' | jq -r --arg secret "$SECRET_NAME" '.[$secret][]')
          echo "repos=$REPOS" >> $GITHUB_OUTPUT

      - name: Sync secret to repositories
        env:
          SECRET_VALUE: ${{ secrets[github.event.inputs.secret_name] }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "$SECRET_VALUE" ]; then
            echo "Error: Secret value not found"
            exit 1
          fi

          echo '${{ steps.get-repos.outputs.repos }}' | while read -r repo; do
            if [ ! -z "$repo" ]; then
              echo "Syncing secret to $repo"
              echo "$SECRET_VALUE" | gh secret set "${{ github.event.inputs.secret_name }}" --body-file - --repo "$repo"
            fi
          done
