name: Propagate Repository Secrets
on:
  workflow_dispatch:

jobs:
  get-mappings:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      
      - id: set-matrix
        run: |
          # Create a matrix of secret names and their target repos
          echo "matrix=$(jq -c '{include: [inputs[] | {secret: key, repos: .}]}' secret-mappings.json)" >> $GITHUB_OUTPUT

  propagate:
    needs: get-mappings
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get-mappings.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Configure GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
          
      - name: Propagate Secret
        run: |
          # The secret value is referenced statically for each matrix job
          SECRET_VALUE="${{ secrets[matrix.secret] }}"
          
          # Process each target repo
          echo '${{ toJson(matrix.repos) }}' | jq -r '.[]' | while read -r repo; do
            if [ ! -z "$repo" ]; then
              echo "Setting ${{ matrix.secret }} for repository $repo"
              echo "$SECRET_VALUE" | gh secret set "${{ matrix.secret }}" --repo "$repo"
            fi
          done
