name: Propagate Repository Secrets
on:
  workflow_dispatch:

jobs:
  propagate-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Configure GitHub CLI
        run: |
          # Use PAT instead of default token for gh CLI authentication
          gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
        
      - name: Process Secret Mappings
        run: |
          # Read the secret mappings
          MAPPINGS=$(cat secret-mappings.json)
          
          # Iterate through each secret in the JSON
          for secret_name in $(echo "$MAPPINGS" | jq -r 'keys[]'); do
            # Reference the secret value using GitHub Actions syntax
            eval "secret_value=\${{ secrets.${secret_name} }}"
            
            # Get the list of target repos for this secret
            repos=$(echo "$MAPPINGS" | jq -r --arg key "$secret_name" '.[$key][]')
            
            # For each target repo, set the secret
            echo "$repos" | while read -r repo; do
              if [ ! -z "$repo" ]; then
                echo "Setting $secret_name for repository $repo"
                echo "$secret_value" | gh secret set "$secret_name" --repo "$repo"
              fi
            done
          done

      - name: Report Status
        run: |
          echo "Secret propagation complete"
